### ISSUE TITLE
lime-compiler install fails

### ISSUE THREAD

**Issue by jouellnyc** [ThreatResponse/lime-compiler#11]
Hi. I am getting the same error on AWS ec2 as well as Ubuntu

uname -a
Linux vagrant 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

uname -a
Linux ip-10-0-2-229.ec2.internal 4.14.173-137.229.amzn2.x86_64 #1 SMP Wed Apr 1 18:06:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# git clone https://github.com/ThreatResponse/lime-compiler.git

# gem build lime-compiler.gemspec
  Successfully built RubyGem
  Name: lime-compiler 
  Version: 0.0.1.pre
  File: lime-compiler-0.0.1.pre.gem

# gem install lime-compiler-0.0.1.pre.gem 
Successfully installed lime-compiler-0.0.1.pre
Parsing documentation for lime-compiler-0.0.1.pre
Installing ri documentation for lime-compiler-0.0.1.pre
Done installing documentation for lime-compiler after 0 seconds
1 gem installed

# lime-compiler 
Traceback (most recent call last):
	11: from /usr/local/bin/lime-compiler:23:in `<main>'
	10: from /usr/local/bin/lime-compiler:23:in `load'
	 9: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/bin/lime-compiler:3:in `<top (required)>'
	 8: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/bin/lime-compiler:6:in `rescue in <top (required)>'
	 7: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/bin/lime-compiler:6:in `require_relative'
	 6: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/lib/lime-compiler/all.rb:2:in `<top (required)>'
	 5: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/lib/lime-compiler/all.rb:2:in `require_relative'
	 4: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/lib/lime-compiler/application.rb:6:in `<top (required)>'
	 3: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/lib/lime-compiler/application.rb:6:in `require_relative'
	 2: from /var/lib/gems/2.5.0/gems/lime-compiler-0.0.1.pre/lib/lime-compiler/gpg.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- gpgme (LoadError)

I followed a few interweb threads; one of which had me try a diff gem version...Now my system in at:

# gem --version
2.7.6

How to confirm my Ruby environments are sane for this?

**Comment by jouellnyc** [comment]
Seems I did not have proper dependencies. chased this for a while ala the 'x/y' problem. Most of the need actions to take ended up coming from:

https://stackoverflow.com/questions/13767725/unable-to-install-gem-failed-to-build-gem-native-extension-cannot-load-such
https://stackoverflow.com/questions/30665912/no-ruby-devel-in-rhel7
https://superuser.com/questions/590808/yum-install-gcc-g-doesnt-work-anymore-in-centos-6-4
https://gist.github.com/yograterol/99c8e123afecc828cb8c

and then doing:
sudo gem install gpgme
sudo gem install aws-sdk
sudo gem install nokogiri
sudo gem install activesupport
sudo gem install docker-api
sudo gem install bundler 

I just kept trying to satisfy the error and hunt down the needed gem ala the 'x/y' problem.
It runs now. 

It does run but errors:

docker_client.rb:7:in `initialize': undefined method `url=' for Docker:Module (NoMethodError)

Nothing on the web fixes that....
